# Generated by Django 5.1.13 on 2025-11-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '00xx_create_core_receiptline'),
    ]

    operations = [
    ]
