# Generated by Django 5.2.6 on 2025-09-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringcart',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recurringcartitem',
            options={'managed': False},
        ),
    ]
