# Generated by Django 5.1.12 on 2025-11-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'managed': True},
        ),
    ]
