# Generated by Django 5.1.13 on 2025-11-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='user',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='core.users'),
        ),
    ]
