# Generated by Django 5.1.6 on 2025-12-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_core_receiptline'),
        ('core', '0002_alter_deliveries_options'),
    ]

    operations = [
    ]
