# Generated by Django 5.1.6 on 2025-08-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliveries_items_orderitems_orders_stores_users_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='FEEDBACK',
        ),
    ]
