# Generated by Django 5.1.6 on 2025-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_code',
            field=models.CharField(default='46d6dd1b', max_length=8, unique=True),
        ),
    ]
