# Generated by Django 5.1.6 on 2025-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_code',
            field=models.CharField(default='f07b23f5', max_length=8, unique=True),
        ),
    ]
