# Generated by Django 5.1.6 on 2025-08-31 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options_alter_chatgroup_group_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatgroup'),
        ),
    ]
