"""
Django settings for GShare project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
from decouple import config

# API key for Google Maps
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY')

# API key for Stripe
STRIPE_SECRET_KEY= config('STRIPE_SECRET_KEY')


# print(config('GOOGLE_MAPS_API_KEY', default='NOT FOUND'))
# print("settings file executed")

FAKE_GEOLOC = config("FAKE_GEOLOC", default=True, cast=bool) 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pg#@x(*0luj+qolr_&4uya(@&+5hbqwzdc+f0zeb_i!k$x6a)l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".elasticbeanstalk.com",
    "www.gshare.me",
    "gshare.me",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.elasticbeanstalk.com",
    "https://gshare.me",
    "https://www.gshare.me",
]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'channels',
    'chat',
    "django_tailwind_cli",
    # "django_browser_reload",
    'django_q',
    # 'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'configurations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.scan_permission',
            ],
        },
    },
]

WSGI_APPLICATION = 'configurations.wsgi.application'
ASGI_APPLICATION = 'configurations.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# use your own database configurations
MYSQL = { "ENGINE": "django.db.backends.mysql", 
            "NAME": os.environ.get("DB_NAME", ""), 
            "USER": os.environ.get("DB_USER", ""), 
            "PASSWORD": os.environ.get("DB_PASSWORD", ""), 
            "HOST": os.environ.get("DB_HOST", ""), 
            "PORT": os.environ.get("DB_PORT", ""), "OPTIONS": {"charset": "utf8mb4"}, 
        }
DATABASES = { "default": MYSQL, 
                "gsharedb": MYSQL, 
            }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',       
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',        
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login' 


# Django Q2 settings
# https://django-q2.readthedocs.io/en/master/
Q_CLUSTER = {
    "name": "gshare",
    "workers": 1,             
    "timeout": 60,            
    "retry": 90,             
    "queue_limit": 50,
    "bulk": 1,
    "orm": "default",
}

# LOGGING CONFIGURATION
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "gshare-live-tracking",
    }
}


INSTALLED_APPS += ["storages"]

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default=None)
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-2")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="gshare-media-prod")
AWS_S3_SIGNATURE_VERSION = "s3v4"

# Files are private; URLs are time-limited (presigned)
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = None

# Don’t overwrite files with same name
AWS_S3_FILE_OVERWRITE = False

# Optional control caching headers
# AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=31536000, public"}

# Default file storage backend
DEFAULT_FILE_STORAGE = "core.storage.PrivateMediaStorage"
# --- end S3 config ---
# (Optional but helpful in dev)
# DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
# FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

GEMINI_API_KEY = config("GEMINI_API_KEY", default="")
GEMINI_RECEIPT_MODEL = "gemini-1.5-flash"   # good + cheap for dev
GEMINI_CHAT_MODEL = "gemini-1.5-flash"  
# --- Celery (dev) ---
# In-memory broker is fine for local testing (no Redis required)
CELERY_BROKER_URL = "memory://"
CELERY_RESULT_BACKEND = "rpc://"